osx_image: xcode8.3

dist: trusty
sudo: required

language: node_js
node_js:
  - "lts/*"

before_script:
    - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
    - sudo apt-get update
    - sudo apt-get install --no-install-recommends -y wine1.8

mono: latest

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist -- --linux --win; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist -- --mac; fi

cache:
  directories:
    - "node_modules"
